# Global base configuration
spring:
  profiles:
    active: dev # Defaults to dev if not specified

  # Common Jackson Formatting
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false

  # Common View Resolver
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp

# MyBatis Common Config
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.idgovern.model

# Server settings
server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful # Industry standard for data integrity